### ISSUE TITLE
wshcopy doesn't work under Python 2.7

### ISSUE THREAD

**Issue by amengus87** [isontheline/webssh.sh#3]
```
python -V
Python 2.7.17

echo "test" | wshcopy 
Traceback (most recent call last):
  File "/usr/local/bin/wshcopy", line 7, in <module>
    from wsh.wshcopy import cli
  File "/usr/local/lib/python2.7/dist-packages/wsh/wshcopy.py", line 44
    print("\033]52;c;" + base64_string + "\a", end='')
                                                  ^
SyntaxError: invalid syntax
```

**Comment by isontheline** [comment]
Fixed by https://github.com/isontheline/webssh.sh/pull/4/files
